// The pricing contract. Do not edit this file; implement
// src/lib/pricing.js (ES module, named export computePrice) so that
// `npm test` passes. Values were computed independently with exact
// decimal arithmetic.
import { describe, expect, it } from "vitest";
import { computePrice } from "../src/lib/pricing.js";

describe("computePrice", () => {
  it("prices a single starter seat", () => {
    expect(computePrice({ plan: "starter", seats: 1, months: 1, addons: [] }))
      .toEqual({ monthly: 9.0, total: 9.0, savings: 0.0 });
  });

  it("prices ten team seats with no discounts", () => {
    expect(computePrice({ plan: "team", seats: 10, months: 1, addons: [] }))
      .toEqual({ monthly: 180.0, total: 180.0, savings: 0.0 });
  });

  it("applies the volume tier marginally from seat 11", () => {
    expect(computePrice({ plan: "team", seats: 11, months: 1, addons: [] }))
      .toEqual({ monthly: 196.2, total: 196.2, savings: 1.8 });
  });

  it("applies both volume tiers marginally past seat 50", () => {
    expect(computePrice({ plan: "enterprise", seats: 51, months: 1, addons: [] }))
      .toEqual({ monthly: 1496.0, total: 1496.0, savings: 136.0 });
  });

  it("applies the annual discount to the whole subtotal", () => {
    expect(computePrice({ plan: "starter", seats: 3, months: 12, addons: [] }))
      .toEqual({ monthly: 21.6, total: 259.2, savings: 64.8 });
  });

  it("stacks volume, addons, and annual discount in order", () => {
    expect(computePrice({ plan: "team", seats: 25, months: 12, addons: [{ id: "sso", pricePerMonth: 25 }] }))
      .toEqual({ monthly: 358.4, total: 4300.8, savings: 1399.2 });
  });

  it("rounds the monthly price half-up to cents before totalling", () => {
    expect(computePrice({ plan: "starter", seats: 11, months: 12, addons: [{ id: "backup", pricePerMonth: 4.99 }] }))
      .toEqual({ monthly: 82.47, total: 989.64, savings: 258.24 });
  });

  it("rejects invalid input", () => {
    expect(() => computePrice({ plan: "gold", seats: 1, months: 1, addons: [] })).toThrow();
    expect(() => computePrice({ plan: "team", seats: 0, months: 1, addons: [] })).toThrow();
    expect(() => computePrice({ plan: "team", seats: 1, months: 6, addons: [] })).toThrow();
  });
});
