//! The executable contract. These tests are the specification's teeth:
//! `cargo test` must pass byte-exact against the goldens in fixtures/.
//! Do not edit this file or the fixtures; implement src/main.rs.

use std::process::{Command, Output};

fn logstat(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_logstat"))
        .args(args)
        .output()
        .expect("failed to launch logstat")
}

fn fixture(name: &str) -> String {
    let path = format!("{}/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name);
    std::fs::read_to_string(path).expect("read fixture")
}

fn log_path() -> String {
    format!("{}/fixtures/access.log", env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn summary_tsv_matches_golden() {
    let out = logstat(&["summary", &log_path()]);
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    assert_eq!(String::from_utf8_lossy(&out.stdout), fixture("expected_summary.tsv"));
}

#[test]
fn summary_json_matches_golden() {
    let out = logstat(&["summary", &log_path(), "--json"]);
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    assert_eq!(String::from_utf8_lossy(&out.stdout), fixture("expected_summary.json"));
}

#[test]
fn filter_5xx_matches_golden() {
    let out = logstat(&["filter", &log_path(), "--status", "5xx"]);
    assert!(out.status.success());
    assert_eq!(String::from_utf8_lossy(&out.stdout), fixture("expected_5xx.txt"));
}

#[test]
fn filter_2xx_get_matches_golden() {
    let out = logstat(&["filter", &log_path(), "--status", "2xx", "--method", "GET"]);
    assert!(out.status.success());
    assert_eq!(String::from_utf8_lossy(&out.stdout), fixture("expected_2xx_get.txt"));
}

#[test]
fn missing_file_exits_1_with_stderr() {
    let out = logstat(&["summary", "/no/such/file.log"]);
    assert_eq!(out.status.code(), Some(1));
    assert!(out.stdout.is_empty(), "nothing on stdout for a missing file");
    assert!(!out.stderr.is_empty(), "the error must be reported on stderr");
}

#[test]
fn usage_errors_exit_2_with_stderr() {
    for bad in [
        vec![],                                              // no subcommand
        vec!["frobnicate", "x.log"],                         // unknown subcommand
        vec!["summary"],                                     // missing file
        vec!["filter", "x.log"],                             // missing --status
        vec!["filter", "x.log", "--status", "9xx"],          // invalid class
    ] {
        let out = logstat(&bad.iter().map(|s| *s).collect::<Vec<_>>());
        assert_eq!(out.status.code(), Some(2), "args {:?} must exit 2", bad);
        assert!(!out.stderr.is_empty(), "args {:?} must explain on stderr", bad);
    }
}
